add debug for build

diff --git a/.github/workflows/front-end.yml b/.github/workflows/front-end.yml
--- a/.github/workflows/front-end.yml
+++ b/.github/workflows/front-end.yml
@@ -13,7 +13,7 @@ jobs:
 
     strategy:
       matrix:
-        node-version: [18.x, 20.x, 22.x]
+        node-version: [22.x]
 
     steps:
     - uses: actions/checkout@v4
@@ -23,16 +23,23 @@ jobs:
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
-        cache-dependency-path: front-end/package-lock.json  # Specify correct lock file path
+        cache-dependency-path: front-end/package-lock.json
 
+    - name: Debug Node.js Version & Dependencies
+      working-directory: front-end
+      run: |
+        node -v
+        npm -v
+        ls -l package-lock.json || echo "package-lock.json NOT FOUND!"
+    
     - name: Install dependencies
       working-directory: front-end
       run: npm ci
-
+      
     - name: Build
       working-directory: front-end
       run: npm run build --if-present
-
+      
     - name: Run Tests
       working-directory: front-end
       run: npm test
